 #### Create arrays with all the data types available in numpy

In [15]:
import numpy as np

##### Integer

In [16]:
arr = np.array([1, 2, 3, 4], dtype = 'int_')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


##### Boolean

In [17]:
arr = np.array([True, False, False, True], dtype = 'bool_')
print(arr)
print(arr.dtype)

[ True False False  True]
bool


##### Float

In [18]:
arr = np.array([1.1, 2.2, 3.3, 4.4], dtype = 'float_')
print(arr)
print(arr.dtype)

[1.1 2.2 3.3 4.4]
float64


##### String

In [19]:
arr = np.array(['a', 'b', 'c', 'd'], dtype = 'S')
print(arr)
print(arr.dtype)

[b'a' b'b' b'c' b'd']
|S1


##### Object

In [20]:
arr = np.array([[1, 2], [True, False], [1.1, 2.2], ['Hari', 'Prakash']], dtype = 'O')
print(arr)
print(arr.dtype)

[[1 2]
 [True False]
 [1.1 2.2]
 ['Hari' 'Prakash']]
object


##### Unicode

In [21]:
arr = np.array([1, 2, 3, 4], dtype = 'U')
print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1


##### Unsigned Integer

In [22]:
arr = np.array([1, 2, 3, 4], dtype = 'uint8')
print(arr)
print(arr.dtype)

[1 2 3 4]
uint8
